name: ADO Workflow

on:
  workflow_call:
    inputs:
      ADO_REPO_URL:
        description: 'Repository URL'
        required: true
        type: string
      BRANCH_NAME:
        description: 'Branch to push in ADO'
        required: true
        type: string

env:
  ADO_REPO_URL: ${{ inputs.ADO_REPO_URL }}
  BRANCH_NAME: ${{ inputs.BRANCH_NAME }}

jobs:
  push_to_ado:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      - name: Setup SSH key
        run: |
          mkdir -p ~/ssh_ado
          echo "${{ secrets.ADO_SSH_KEY }}" | tr -d '\r' > ~/ssh_ado/id_rsa_ado
          echo "" >>  ~/ssh_ado/id_rsa_ado
          chmod 600 ~/ssh_ado/id_rsa_ado
          cat ~/ssh_ado/id_rsa_ado
          ssh-keyscan -t rsa www.dev.diplanung.de >> ~/ssh_ado/known_hosts

      - name: Configure Git SSH command
        run: |
          git config core.sshCommand "ssh -i ~/.ssh/id_rsa_ado"

      - name: Push to ADO
        run: |
          git remote add ADO $ADO_REPO_URL
          git fetch ADO
          git checkout -b temporary_branch
          git push ADO temporary_branch:${{ env.BRANCH_NAME }}

      - name: Delete ssh key
        run: |
          rm -rf ~/.ssh/id_rsa_ado