on:
  workflow_call:
    inputs:
      ADO_REPO_URL:
        description: 'repository url'
        required: true
        type: string
    secrets:
      ADO_TOKEN:
        required: true

env:
  ADO_TOKEN: ${{ secrets.ADO_TOKEN }}
  ADO_REPO_URL: ${{ inputs.ADO_REPO_URL }}

jobs:
  compare_with_ado:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      - name: Compare with ADO
        run: |
          git remote add ADO $ADO_REPO_URL
          git -c http.extraheader="Authorization: Basic $ADO_TOKEN" fetch ADO main
          git diff ADO/main..HEAD
