on:
  workflow_call:
    inputs:
      ignore_path:
        description: 'path to directories and files that schould be ignored'
        type: string
        required: false
      gpg_user_name:
        description: 'username for gpg signing'
        required: true
        type: string
    secrets:
      GPG_EMAIL:
        required: true


jobs:
  cancel:
    name: 'Cancel Previous Runs'
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
        -   uses: styfle/cancel-workflow-action@0.12.1
            with:
                workflow_id: "FE_headerWriter"
                access_token: ${{ secrets.GITHUB_TOKEN }}

  FE_headerWriter:
    runs-on: ubuntu-20.04
    steps:

      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: download headerWriter
        run: |
         wget https://raw.githubusercontent.com/demos-europe/demosplan-workflows/main/.github/headerWriter.py -O .github/headerWriter.py

      - name: Run headerWriter
        run: |
          python3 .github/headerWriter.py -p  ${{ github.workspace }} -i  ${{ inputs.ignore_path }} -a -v
        shell: bash

      - name: delete headerWriter
        run: rm .github/headerWriter.py
        shell: bash

      - name: Configure git
        run: |
          git config  user.email ${{ secrets.GPG_EMAIL }}
          git config  user.name ${{ inputs.gpg_user_name }}
      - name: Commit
        run: |
              git pull
              if ! git diff --exit-code; then
              git add .
              git commit -m "style: Update license header"
              git push
              fi